"""add unique constraint on orders user_id client_order_id

Revision ID: 079188f8c39b
Revises: 6159ee881031
Create Date: 2026-07-25 09:22:53.249261

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '079188f8c39b'
down_revision: Union[str, None] = '6159ee881031'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_orders_user_client_order', 'orders', ['user_id', 'client_order_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_orders_user_client_order', 'orders', type_='unique')
    # ### end Alembic commands ###
