"""add withdrawal/deposit idempotency indexes

Revision ID: 25165f81480b
Revises: 763d787eabf1
Create Date: 2026-09-12 10:13:51.713261

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '25165f81480b'
down_revision: Union[str, None] = '763d787eabf1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('uq_transactions_deposit_ref', 'transactions', ['reference_id'], unique=True, postgresql_where=sa.text("type = 'deposit' AND reference_id IS NOT NULL"))
    op.create_index('uq_transactions_withdrawal_ref', 'transactions', ['reference_id'], unique=True, postgresql_where=sa.text("type = 'withdrawal' AND reference_id IS NOT NULL"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_transactions_withdrawal_ref', table_name='transactions', postgresql_where=sa.text("type = 'withdrawal' AND reference_id IS NOT NULL"))
    op.drop_index('uq_transactions_deposit_ref', table_name='transactions', postgresql_where=sa.text("type = 'deposit' AND reference_id IS NOT NULL"))
    # ### end Alembic commands ###
