"""add alert pending partial indexes

Revision ID: 3c95a685f3f9
Revises: 25165f81480b
Create Date: 2026-09-12 10:35:19.968565

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3c95a685f3f9'
down_revision: Union[str, None] = '25165f81480b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_alerts_market_pending', 'alerts', ['market_id'], unique=False, postgresql_where=sa.text('triggered = false'))
    op.create_index('ix_alerts_user_pending', 'alerts', ['user_id'], unique=False, postgresql_where=sa.text('triggered = false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_alerts_user_pending', table_name='alerts', postgresql_where=sa.text('triggered = false'))
    op.drop_index('ix_alerts_market_pending', table_name='alerts', postgresql_where=sa.text('triggered = false'))
    # ### end Alembic commands ###
