"""add is_admin to users

Revision ID: c1794894c63a
Revises: 079188f8c39b
Create Date: 2026-07-25 10:00:41.870226

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c1794894c63a'
down_revision: Union[str, None] = '079188f8c39b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column('users', sa.Column('is_admin', sa.Boolean(), nullable=True, server_default='false'))
    op.execute("UPDATE users SET is_admin = false WHERE is_admin IS NULL")
    op.alter_column('users', 'is_admin', nullable=False)



def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_admin')
    # ### end Alembic commands ###
